export const allExercises = {
  pushUpsAll: [
    "Atomic",
    "Bag Pull",
    "Burpee",
    "Elevator Pause",
    "Kick throughs",
    "Narrow",
    "Negatives",
    "One Foot",
    "Pike",
    "Planche",
    "Plank Walk",
    "Plyo",
    "Renegade",
    "Shoulder Tap",
    "Split Diamond",
    "Superman",
    "Wide",
  ],
  upper2: [
    "Bent Over Row",
    "Bentover Flys",
    "Cable Cross",
    "Cable Flys",
    "Cat Plank",
    "Chest Press",
    "Crocodiles",
    "Dead Hang",
    "Deadbugs",
    "Deadlifts",
    "Face Pulls",
    "Gorilla Rows",
  ],
  upper3: [
    "Hyper Extension",
    "Inverted Rows",
    "Lat Pull Down",
    "Monkey Run",
    "Narrow Grip Pullups",
    "Plated Prayers",
    "Pull ups",
    "Rear Delt Row",
    "Scap pull-ups",
    "Seated Row",
    "Sidebends",
    "Single arms hangs",
  ],
  upperAll: [
    "Bent Over Row",
    "Bentover Flys",
    "Cable Cross",
    "Cable Flys",
    "Cat Plank",
    "Chest Press",
    "Crocodiles",
    "Dead Hang",
    "Deadbugs",
    "Deadlifts",
    "Face Pulls",
    "Gorilla Rows",
    "Hyper Extension",
    "Inverted Rows",
    "Lat Pull Down",
    "Monkey Run",
    "Narrow Grip Pullups",
    "Plated Prayers",
    "Pull ups",
    "Rear Delt Row",
    "Scap pull-ups",
    "Seated Row",
    "Sidebends",
    "Single arms hangs",
  ],
  upperHiit: [
    "Atomic PushUps",
    "Bag Pull Throughs",
    "Burpees",
    "Kick throughs",
    "Narrow",
    "Plank Walk",
    "Plyo push ups",
    "Push Up Total",
    "Renegade Push ups",
    "Shoulder Taps",
    "Split Diamonds",
    "Superman pushups",
    "Wide push ups",
    "Bent Over Row",
    "Bentover Flys",
    "Cable Cross",
    "Cable Flys",
    "Cat Plank",
    "Chest Press",
    "Crocodiles",
    "Dead Hang",
    "Deadbugs",
    "Deadlifts",
    "Face Pulls",
    "Gorilla Rows",
    "Hyper Extension",
    "Inverted Rows",
    "Lat Pull Down",
    "Monkey Run",
    "Narrow Grip Pullups",
    "Plated Prayers",
    "Pull ups",
    "Rear Delt Row",
    "Scap pull-ups",
    "Seated Row",
    "Sidebends",
    "Single arms hangs",
  ],
  legs1: [
    "Abductions",
    "Box Jumps",
    "Bulgarians ",
    "Chair Hold",
    "Curtsy Lunge",
    "DB Squat to Press",
    "Duck walk",
    "Goblet Squats",
    "Ham Curls",
    "Isometric",
    "Jump Squats",
    "Kettle Bell Swings",
    "Kick to Burpee Hops",
    "Knees Over Lunge",
    "L-Sits",
    "Lunge Kick Press",
  ],
  legs2: [
    "Lunge",
    "Pistols",
    "Pulse",
    "Rev Lunge",
    "Shuttle run",
    "Side Walks",
    "SL Deadlifts",
    "Squat and clean",
    "Squat-Jumps",
    "Squats",
    "Suitcase Swings",
    "Sumo Walk",
    "Switch lunge",
    "Tuck Jump",
    "Walking Lunge",
    "Warrior Lunges",
  ],
  legsAll: [
    "Abductions",
    "Box Jumps",
    "Bulgarians ",
    "Chair Hold",
    "Curtsy Lunge",
    "DB Squat to Press",
    "Duck walk",
    "Goblet Squats",
    "Ham Curls",
    "Isometric",
    "Jump Squats",
    "Kettle Bell Swings",
    "Kick to Burpee Hops",
    "Knees Over Lunge",
    "L-Sits",
    "Lunge Kick Press",
    "Lunge",
    "Pistols",
    "Pulse",
    "Rev Lunge",
    "Shuttle run",
    "Side Walks",
    "SL Deadlifts",
    "Squat and clean",
    "Squat-Jumps",
    "Squats",
    "Suitcase Swings",
    "Sumo Walk",
    "Switch lunge",
    "Tuck Jump",
    "Walking Lunge",
    "Warrior Lunges",
  ],
  core3: [
    "Ball-Slams",
    "Bear Crawl",
    "Bicycle Crunches",
    "Black Widow",
    "Broad Launch",
    "Bunny Hops",
    "Cork Screws",
    "Crow Crane",
    "Crunch Holds",
    "Headstand",
    "High knees",
    "Landmine Thrusts",
    "Leg Raises",
    "Mountain Climbers",
    "Mule Kicks",
    "Oblique Circles",
  ],
  core4: [
    "Plank",
    "Polov Press",
    "Renegade Rows",
    "Russian Twists",
    "See saws",
    "Side Plank Thread to T",
    "Single Arm Plank",
    "Sit-up elbow thrusts",
    "Skin the cats",
    "Slam & Sprall",
    "Superman-Walkouts",
    "V-sit",
    "V-up Toe Touch",
    "W Lever",
    "Wall Slams",
    "Weighted V ups",
  ],
  coreAll: [
    "Ball-Slams",
    "Bear Crawl",
    "Bicycle Crunches",
    "Black Widow",
    "Broad Launch",
    "Bunny Hops",
    "Cork Screws",
    "Crow Crane",
    "Crunch Holds",
    "Headstand",
    "High knees",
    "Landmine Thrusts",
    "Leg Raises",
    "Mountain Climbers",
    "Mule Kicks",
    "Oblique Circles",
    "Plank",
    "Polov Press",
    "Renegade Rows",
    "Russian Twists",
    "See saws",
    "Side Plank Thread to T",
    "Single Arm Plank",
    "Sit-up elbow thrusts",
    "Skin the cats",
    "Slam & Sprall",
    "Superman-Walkouts",
    "V-sit",
    "V-up Toe Touch",
    "W Lever",
    "Wall Slams",
    "Weighted V ups",
  ],
  ideas: [
    "Ball",
    "Barbell",
    "Bike",
    "Bosu",
    "Boxing",
    "Calisthenics",
    "Cardio",
    "Dropset",
    "Dumbbells",
    "Eccentric",
    "Extincion",
    "Isometric Hold",
    "Kettlebell",
    "Ladder",
    "Landmine",
    "Metabolic",
    "Pause",
    "PHA",
    "Plate",
    "Plyo Box",
    "Plyometrics",
    "Pulse",
    "Rope",
    "Sandbag",
    "Skater",
    "Slams",
    "Sledge",
    "Step",
    "TRX",
    "Upper Cuts",
    "Waves",
  ],
  arms: [
    "Arnolds",
    "Battle Ropes",
    "Bicep Curls",
    "Chin ups",
    "Dips",
    "Extensions",
    "Frontals",
    "Hammer Curls",
    "Head stand",
    "L-sit Dips",
    "Laterals",
    "Pull Overs",
    "Rev Curls",
    "ShoulderPress",
    "Skull Crushers",
    "Straight Arm Pulldowns",
    "Tricep Pull Downs",
  ],
}
